export default {
  login: "donnemartin",
  id: 5458997,
  node_id: "MDQ6VXNlcjU0NTg5OTc=",
  avatar_url: "https://avatars2.githubusercontent.com/u/5458997?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/donnemartin",
  html_url: "https://github.com/donnemartin",
  followers_url: "https://api.github.com/users/donnemartin/followers",
  following_url:
    "https://api.github.com/users/donnemartin/following{/other_user}",
  gists_url: "https://api.github.com/users/donnemartin/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/donnemartin/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/donnemartin/subscriptions",
  organizations_url: "https://api.github.com/users/donnemartin/orgs",
  repos_url: "https://api.github.com/users/donnemartin/repos",
  events_url: "https://api.github.com/users/donnemartin/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/donnemartin/received_events",
  type: "User",
  site_admin: false,
  name: "Donne Martin",
  company: "@facebook",
  blog: "http://donnemartin.com/",
  location: "Washington, D.C.",
  email: null,
  hireable: true,
  bio: "Software Engineer @facebook",
  twitter_username: "donne_martin",
  public_repos: 27,
  public_gists: 0,
  followers: 9970,
  following: 3,
  created_at: "2013-09-14T15:45:40Z",
  updated_at: "2020-07-11T20:53:29Z",
};
