export default {
  login: "aravind-alpha",
  id: 53869607,
  node_id: "MDQ6VXNlcjUzODY5NjA3",
  avatar_url: "https://avatars2.githubusercontent.com/u/53869607?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/aravind-alpha",
  html_url: "https://github.com/aravind-alpha",
  followers_url: "https://api.github.com/users/aravind-alpha/followers",
  following_url:
    "https://api.github.com/users/aravind-alpha/following{/other_user}",
  gists_url: "https://api.github.com/users/aravind-alpha/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/aravind-alpha/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/aravind-alpha/subscriptions",
  organizations_url: "https://api.github.com/users/aravind-alpha/orgs",
  repos_url: "https://api.github.com/users/aravind-alpha/repos",
  events_url: "https://api.github.com/users/aravind-alpha/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/aravind-alpha/received_events",
  type: "User",
  site_admin: false,
  name: "Aravind",
  company: "Self",
  blog: "",
  location: "India",
  email: null,
  hireable: null,
  bio: "Software Engineer",
  twitter_username: null,
  public_repos: 7,
  public_gists: 0,
  followers: 2,
  following: 3,
  created_at: "2019-08-07T14:53:57Z",
  updated_at: "2020-07-17T01:54:46Z",
};
